=== api-evangelist/akamai-api-security/json-schema/api-security-problem-details-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/akamai-api-security/refs/heads/main/json-schema/api-security-problem-details-schema.json",
  "title": "problem-details",
  "description": "Details the errors you can receive.",
  "type": "object",
  "properties": {
    "detail": {
      "description": "The detailed error message.",
      "type": "string"
    },
    "fieldErrors": {
      "additionalProperties": {
        "description": "Fields that provide additional details about the problem.",
        "type": "string"
      },
      "description": "Pointers to fields for which invalid input was provided, whose values are messages detailing the reason this input was invalid for this field.",
      "type": "object"
    },
    "instance": {
      "description": "The non-referenceable URI that indicates the error instance.",
      "example": "https://problems.luna.akamaiapis.net/api-definitions/error-instances/d54686b5-21cb-4ab7-a8d6-a92282cf1749",
      "type": "string"
    },
    "status": {
      "description": "The HTTP status code.",
      "example": 404,
      "type": "integer"
    },
    "title": {
      "description": "The error title.",
      "example": "Not Found",
      "type": "string"
    },
    "type": {
      "description": "The URL for the error type.",
      "example": "https://problems.luna.akamaiapis.net/api-definitions/error-types/NOT-FOUND",
      "type": "string"
    }
  },
  "required": [
    "title",
    "type",
    "detail",
    "instance",
    "status"
  ],
  "additionalProperties": true
}

=== api-evangelist/akamai-api-security/examples/api-security-problem-details-example.json
{
  "detail": "example-value",
  "fieldErrors": {},
  "instance": "https://problems.luna.akamaiapis.net/api-definitions/error-instances/d54686b5-21cb-4ab7-a8d6-a92282cf1749",
  "status": 404,
  "title": "Not Found",
  "type": "https://problems.luna.akamaiapis.net/api-definitions/error-types/NOT-FOUND"
}
